import { MigrationInterface, QueryRunner, Table } from 'typeorm'

export class Motivo_Submotivo_Assunto_1688096123706 implements MigrationInterface {
  public async up (queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(new Table({
      name: 'MotivoContato',
      columns: [
        {
          name: 'CodigoMotivoContato',
          type: 'integer',
          isGenerated: true,
          generationStrategy: 'increment',
          isPrimary: true
        },
        {
          name: 'Descricao',
          type: 'varchar'
        }
      ]
    }), true)

    await queryRunner.createTable(new Table({
      name: 'SubMotivoContato',
      columns: [
        {
          name: 'CodigoSubMotivoContato',
          type: 'integer',
          isGenerated: true,
          generationStrategy: 'increment',
          isPrimary: true
        },
        {
          name: 'CodigoMotivoContato',
          type: 'integer',
          isPrimary: true
        },
        {
          name: 'Descricao',
          type: 'varchar'
        }
      ],
      foreignKeys: [
        {
          name: 'FK_SubMotivoContato_MotivoContato_CodigoMotivoContato',
          columnNames: ['CodigoMotivoContato'],
          referencedColumnNames: ['CodigoMotivoContato'],
          referencedTableName: 'MotivoContato'
        }
      ]
    }), true)

    await queryRunner.createTable(new Table({
      name: 'AssuntoContato',
      columns: [
        {
          name: 'CodigoAssuntoContato',
          type: 'integer',
          isGenerated: true,
          generationStrategy: 'increment',
          isPrimary: true
        },
        {
          name: 'CodigoSubMotivoContato',
          type: 'integer',
          isPrimary: true
        },
        {
          name: 'Descricao',
          type: 'varchar'
        }
      ],
      foreignKeys: [
        {
          name: 'FK_AssuntoContato_SubMotivoContato_CodigoSubMotivoContato',
          columnNames: ['CodigoSubMotivoContato'],
          referencedColumnNames: ['CodigoSubMotivoContato'],
          referencedTableName: 'SubMotivoContato'
        }
      ]
    }), true)

    //* ********************************* */
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Venda\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Logística Omnichannel\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Promoção\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Acesso ao Planograma\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Sprinklr\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Planograma\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Institucional\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Atendimento\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Vitrinismo/Ambientação\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Software\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Software Omnichannel\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Arquitetura e SGPC\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Jurídico\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Material de Ciclo\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Financeiro\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Aspectos Comerciais\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Hardware\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Field Service\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'LGPD\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Seguro Empresarial\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Orientações de Montagem Loja\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Embalagem\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Uniforme\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Auditoriade Lojas\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Fachada Secundária e Tapume\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Regras de Negócios QDB\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Regras de Negócios\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Documentação\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Incentivos\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Logística Transportadora\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Abastecimento\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Serviços\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Agendamento de Make\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Produtos\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Recebimento e Problemas no Enxoval VM\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Clube Viva\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Precificador\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Campanhas & Promoções\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Infraestrutura de Tecnologia\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Compra\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Estoque\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Cadastros\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Gestão de Resultados\')')
    await queryRunner.query('INSERT INTO MotivoContato (Descricao) VALUES (\'Ambientação\')')

    //* ********************************* */
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (1, \'Iniciar ou Atualizar Sistemas e Dispositivos\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (1, \'Abrir e Fechar o Caixa\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (1, \'Aplicar Desconto ou Promoção\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (1, \'Cadastrar, Consultar e Pontuar Fidelidade\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (1, \'Cancelar uma Venda\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (1, \'Carregar ou Consultar Cartão Presente\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (1, \'Consultar Relatórios\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (1, \'Criar, Editar e Resgatar Pré-Venda\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (1, \'Emitir ou Reemitir Cupom\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (1, \'Emitir Vale-Troca\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (1, \'Identificar Cliente e Vendedor\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (1, \'Incluir Produtos\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (1, \'Realizar Pagamento\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (1, \'Resgatar Pedido Omni\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (2, \'Retire em Loja\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (2, \'Prazo de entrega\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (2, \'Intelipost\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (2, \'Abrangência\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (3, \'Agendamento de serviços\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (3, \'Ação Regional\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (3, \'Ação de Fluxo QDB\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (3, \'Ação de Fluxo\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (4, \'Acesso\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (5, \'Plataforma\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (5, \'Funcionalidade\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (5, \'Conteúdos e Publicações\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (5, \'Acesso\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (6, \'Montagem\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (6, \'Acesso\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (7, \'Reciclagem\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (7, \'Pesquisa\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (7, \'IAF\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (7, \'Eventos Comerciais\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (7, \'Convenção Franqueado\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (8, \'Validação Atendimento\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (8, \'Queda - Ligação\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (8, \'Queda - Conexão\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (8, \'Parcerias\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (8, \'Multimarcas: VD do futuro\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (8, \'Ligação - Transferência\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (8, \'Chat - Transferência\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (8, \'Duvidas sobre OUI\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (9, \'Ambientação\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (10, \'APP\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (10, \'E-Sitef\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (10, \'E-Sitef/Gera\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (10, \'Gera\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (10, \'Gera Eudora\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (10, \'Google governança\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (10, \'Internet\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (10, \'Linx\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (10, \'Mobshop\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (10, \'Nova extranet\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (10, \'PDV Clisitef\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (10, \'Nova extranet\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (10, \'Portais\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (10, \'Portal\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (10, \'Precificador Zebra\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (10, \'TEF\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (10, \'Totvs\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (10, \'Windows\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (11, \'Retire em Loja\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (11, \'Entrega pela VD\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (2, \'Abrangência\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (2, \'Intelipost\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (2, \'Prazo de entrega\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (2, \'Retire em Loja\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (12, \'SGPC\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (12, \'Arquitetura\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (13, \'Judicial\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (13, \'Assessoria\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (13, \'Procon\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (14, \'Bíblia de Preços\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (14, \'Guia do Ciclo Digital\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (14, \'Guia do Ciclo Digital QDB\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (14, \'Materiais Revendedor\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (14, \'Tabela BSO\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (15, \'Boleto\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (15, \'Gerenciar Contas a Pagar\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (15, \'Gerenciar Fluxo de Caixa\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (15, \'Nota de Débito\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (15, \'Nota Fiscal\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (15, \'Plano de Midia Regional\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (16, \'Características\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (16, \'Código/Composição\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (16, \'Queixa Técnica\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (17, \'Computador\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (17, \'Equipamentos / Conectividade\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (17, \'Equipamentos / Rede\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (17, \'Infraestrutura Tecnológica\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (17, \'Rádio\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (18, \'Computador\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (18, \'Equipamentos / Conectividade\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (18, \'Equipamentos / Fiscais\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (18, \'Equipamentos / Impressora\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (18, \'Equipamentos / PDV\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (18, \'Equipamentos / Som\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (18, \'Equipamentos / Telefonia\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (18, \'Falha Linha Móvel\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (19, \'Contato sobre LGPD\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (20, \'Contrato\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (21, \'Guia de Ambientação\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (21, \'Empilhamento embalagens e kits\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (21, \'Display\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (22, \'Dúvidas/Problemas\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (23, \'Fornecedor\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (23, \'Dúvidas/Problemas\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (24, \'Dúvidas/Problemas\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (25, \'Dúvidas sobre impressão e aplicação\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (26, \'Regras de Negócios\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (27, \'Entrega pela VD\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (27, \'Insumos\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (27, \'Retire em Loja\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (28, \'Órgãos Fiscalizadores\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (29, \'Inscrição\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (29, \'Portal\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (29, \'Premiação\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (29, \'Regulamento\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (29, \'Resultado\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (29, \'TÔ QUE TÔ\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (30, \'Intelipost\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (31, \'Irregularidade\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (31, \'Portal de Devolução\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (31, \'Transportadora\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (32, \'Maquiagem completa\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (33, \'Minha rotina Botik\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (34, \'Marcas do Coração\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (35, \'Peças do Ciclo ou Permanentes\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (35, \'Recebimento do enxoval (antilhas)\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (36, \'Pontuação/Bloqueio\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (37, \'Preço\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (38, \'Promoções Exclusivas (CRM)\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (39, \'Coletores de Inventário\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (39, \'Computador\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (39, \'Conectividade de Rede\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (39, \'Impressora Precificador\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (39, \'Impressoras Convencionais\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (39, \'Rádio\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (39, \'Sistema Operacional\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (39, \'Softwares homologados\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (40, \'Avaliar Sugestão de Compra\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (40, \'Consultar ou acompanhar pedido\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (40, \'Consultar ou Cancelar Pendências\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (40, \'Criar, alterar ou cancelar Pedido\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (40, \'Enviar Pedido para Indústria\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (40, \'Rastrear Pedido\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (41, \'Configurar Estoque Negativo e Estoque Mínimo\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (41, \'Consultar Histórico de Movimentação\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (41, \'Consultar Posição de Estoque\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (41, \'Efetuar Devolução\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (41, \'Realizar e Consultar Inventário\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (42, \'Gerenciar Cadastro de Funcionário\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (42, \'Realizar e Consultar Inventário\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (43, \'Gerenciar Boti Expert\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (43, \'Gerenciar BSO\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (43, \'Gerenciar Clube Viva\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (43, \'Gerenciar Dash Comercial\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (43, \'Gerenciar IAF\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (43, \'Gerenciar Plataforma de Gestão Integrada\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (43, \'Gerenciar Plataforma do Franqueado\')')
    await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (44, \'Gerenciar Ruptura\')')
    // await queryRunner.query('INSERT INTO SubMotivoContato (CodigoMotivoContato, Descricao) VALUES (45, \'Precificador\')')

    //* ********************************* */
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (1, \'-\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (2, \'--\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (3, \'Acesso\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (4, \'Acesso  - Loja digital\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (5, \'Acesso ao Portal de Devolução\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (6, \'Acesso Usuário Sistemas\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (7, \'Acessórios\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (8, \'ADM Vendas - Erro Sistêmico\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (9, \'ADM Vendas - Painel Indicadores\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (10, \'Alíquota do Produto\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (11, \'Alteração de Clube\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (12, \'Alterações/ Orientações\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (13, \'Alterar Pedido de Compra\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (14, \'Análise\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (15, \'Antilhas\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (16, \'App Omni\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (17, \'APP Supervisor\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (18, \'Aquisição - Switch\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (19, \'Aquisição - Wi-Fi\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (20, \'Atendimento\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (21, \'Atendimento - Erro Sistêmico\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (22, \'Ativação\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (23, \'Atividade\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (24, \'Atraso/Divergente\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (25, \'Atualização/Validação\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (26, \'Aumentar/Reduzir prazo de entrega\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (27, \'Aumentar/Reduzir prazo de entrega\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (28, \'Autoatendimento Franqueado\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (29, \'Autosolução\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (30, \'Baixa de Pagamento/Indisponível\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (31, \'Botilike\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (32, \'Botioutlet\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (33, \'Botiweb\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (34, \'Botiweb/Extranet\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (35, \'Brinde/PRM\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (36, \'Cadastrar Fidelidade\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (37, \'Cadastro\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (38, \'Cadastro\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (39, \'Cadastro\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (40, \'Cadastro\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (41, \'Cadastro - Alocação colaborador\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (42, \'Cadastro - Erro Sistêmico\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (43, \'Cadastro - Grupo Econômico\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (44, \'Cadastro - Intenção de Revenda\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (45, \'Cadastro - Loja digital\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (46, \'Cadastro - Revendedor/Colaborador\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (47, \'Cadastro - Transferência revendedora\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (48, \'Cadastro CPLV\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (49, \'Cadastro de Produto\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (50, \'Cadastro de Produto\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (51, \'Cadastro de Produto\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (52, \'Cadastros\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (53, \'Cálamo BA\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (54, \'Cálamo CE\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (55, \'Cálamo MG\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (56, \'Cálamo Registro\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (57, \'Cálamo RJ\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (58, \'Cancelamento de Venda - Equipamento SAT\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (59, \'Cancelamento de Venda - LINX PDV\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (60, \'Cancelamento de Venda - TOTVS PDV\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (61, \'Cancelar Pedido de Compra\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (62, \'Cards Digitais/Email\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (63, \'Carregar Cartão Presente - LINX PDV\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (64, \'Carregar Cartão Presente - SYSPDV\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (65, \'Carregar Cartão Presente - TOTVS PDV\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (66, \'Cartão Online\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (67, \'Cartão Presente - Configurar Cartão Presente\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (68, \'Cashback\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (69, \'Catalogos VD/Folheteria\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (70, \'Chip Claro - POS\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (71, \'Chip Especifico - POS\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (72, \'Chip Oi - POS\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (73, \'Chip Tim - POS\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (74, \'Cobrança Infraestrutura tecnológica\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (75, \'Código Promocional\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (76, \'Coletor de Inventário\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (77, \'Composição\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (78, \'Comprovante de entrega\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (79, \'Comprovante de entrega\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (80, \'Computador\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (81, \'Comunicações ER/Guia Ambientação\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (82, \'Conectividade Web \')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (83, \'Configurar Estoque Negativo\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (84, \'Consultar Inventário\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (85, \'Consultar Inventário\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (86, \'Consultar Inventário\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (87, \'Consultar Movimentação de Entrada\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (88, \'Consultar Movimentação de Saída\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (89, \'Consultar NF ou Espelho\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (90, \'Consultar Posição Atual de Estoque\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (91, \'Conta Derrubada\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (92, \'Contas a Receber - CC Residual\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (93, \'Contas a Receber - Erro Sistêmico\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (94, \'Contas a Receber - Integração Bancos\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (95, \'Contas a Receber - Títulos\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (96, \'Contencioso\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (97, \'Conteúdo\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (98, \'Conteúdo\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (99, \'Conteúdo\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (100, \'CREDENCIAMENTO CARTÃO PRESENTE - Cadastro de Franquia\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (101, \'Criar Pré-Venda - LINX Microterminal\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (102, \'Criar Pré-Venda - TOTVS Microterminal\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (103, \'Cuidados Pessoais\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (104, \'Desconto Manual no Item\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (105, \'Desconto Manual no Total\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (106, \'Devolução\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (107, \'Devolução\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (107, \'Devolução do Equipamento - Loja/VD\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (108, \'Dificuldade nas postagens\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (109, \'Digitação Manual do Produto\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (110, \'Divergência de módulos\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (111, \'Divergencia/ Não disponivel\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (112, \'Divergencia/ Não disponivel\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (113, \'Dúvida missões - Loja digital\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (114, \'Dúvidas\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (115, \'Dúvidas\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (116, \'Dúvidas\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (117, \'Dúvidas\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (118, \'Dúvidas\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (119, \'Dúvidas\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (120, \'Dúvidas\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (121, \'Dúvidas de Acesso\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (122, \'Dúvidas de Acesso\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (123, \'Dúvidas de Negócios Geral\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (124, \'Dúvidas sobre projetos/ obra de todos os modelos de PDV\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (125, \'Embratel - 4G\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (126, \'Embratel - Banda Larga\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (127, \'Embratel - MPLS\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (128, \'Embratel - Satélite\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (129, \'Emissão de Vale-Troca\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (130, \'Emissão/Reemissão de Cupom\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (131, \'Emissão/Reemissão de Cupom\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (132, \'Entrega\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (133, \'Enviar Pedido para Indústria\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (134, \'Envio de comunicação - Não recebimento por divergência no Inventário\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (135, \'Equipamento em garantia - Falhas Em Periféricos\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (136, \'Equipamento em garantia - Não Liga\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (137, \'Equipamento em garantia - No Break\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (138, \'Equipamento em garantia - Volta de Imagem\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (139, \'Equipamento MFE\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (140, \'Equipamento MFE\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (141, \'Equipamento Microterminal\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (142, \'Equipamento SAT\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (143, \'Erro Pinpad - Mensagem: 31 \')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (144, \'Erro/Indisponibilidade\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (145, \'Estoque\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (146, \'Estoque Lógico\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (147, \'EUD - Falhas Em Periféricos\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (148, \'EUD - No Break\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (149, \'Fachada secundária\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (150, \'Falha\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (151, \'Falha\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (152, \'Falha - Instore\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (153, \'Falha - Pdv Totvs\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (154, \'Falha - Player\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (155, \'Falha / indisponível\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (156, \'FALHA AMPLIFICADOR DE SOM\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (157, \'Falha AP/Cabos/Rack/Router/Switch\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (158, \'Falha Celular\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (159, \'Falha CEST\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (160, \'FALHA CONECTIVIDADE (BANDA LARGA) - Rede\')')
    await queryRunner.query('INSERT INTO AssuntoContato (CodigoSubMotivoContato, Descricao) VALUES (161, \'Falha de Comunicação - PINPAD\')')
  }

  public async down (queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable('AssuntoContato')
    await queryRunner.dropTable('SubMotivoContato')
    await queryRunner.dropTable('MotivoContato')
  }
}
