on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "fix/**"
      - "release/**"
    paths-ignore:
      - "**/*.md"
      - ".scafflater/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - ".scafflater/**"
  workflow_dispatch:

name: Standard

env:
  app_name: "{{parameters.component}}"
  aws_region_prd: "{{parameters.domainInfo.aws.prd.default-region}}"
  enable_api_gateway: "{{parameters.enableApiGateway}}"
  enable_vpc: "{{parameters.enableVpc}}"
  namespace: "{{parameters.system}}"
  value_stream: "{{parameters.domain}}"

jobs:
  ci:
    name: CI - Build and Test
    runs-on: ["self-hosted", "{{parameters.domainInfo.github.runner-group}}"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
          registry-url: https://npm.pkg.github.com/
      - name: Install Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: $\{{ secrets.GHA_PACKAGES }}
      # Para o hackathon desabilitamos estes passos
      # - name: Lint
      #   run: npm run lint
      # - name: Test
      #   run: npm test
      # - name: Sonar Analysis
      #   uses: sonarsource/sonarcloud-github-action@master
      #   if: $\{{ vars.SONAR_ENABLED == 'true' }}
      #   env:
      #     GITHUB_TOKEN: $\{{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: $\{{ secrets.SONARCLOUD_TOKEN }}
  cd_prd:
    name: CD - PRD
    if: $\{{ success() && github.event_name != 'pull_request' && github.actor != 'dependabot[bot]' }}
    runs-on: ["self-hosted", "{{parameters.domainInfo.github.runner-group}}"]
    needs: [ci]
    environment:
      name: prd
    {{#if parameters.enableApiGateway}}
      url: $\{{ steps.actions-cd-app.outputs.environmentUrl }}
    {{/if}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy Infra
        uses: gbhackathon/actions-cd-eks@v1
        id: actions-cd-infra
        with:
          appName: $\{{ env.app_name }}
          awsRegion: $\{{ env.aws_region_prd }}
          environment: prd
          namespace: $\{{ env.namespace }}
          type: infra
          vs: $\{{ env.value_stream }}
      - name: Deploy Serverless
        uses: gbhackathon/actions-cd-serverless@v3
        id: actions-cd-app
        with:
          appName: $\{{ env.app_name }}
          enableApiGateway: $\{{ env.enable_api_gateway }}
          enableVpc: $\{{ env.enable_vpc }}
          environment: prd
          nodeAuthToken: $\{{ secrets.GHA_PACKAGES }}
          vs: $\{{ env.value_stream }}
